CREATE TABLE `nas` (
  `NAS_DATE` date DEFAULT NULL,
  `NAS_OPEN` decimal(15,2) DEFAULT NULL,
  `NAS_CLOSE` decimal(15,2) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `sse` (
  `SZ_DATE` date DEFAULT NULL,
  `SZ_OPEN` decimal(15,2) DEFAULT NULL,
  `SZ_CLOSE` decimal(15,2) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
